service:
  name: html2amp
# app and org for use with dashboard.serverless.com
app: html2amp
org: ettenger

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  amp:
    handler: src/handler.amp
    events:
      - http:
          method: get
          path: amp
  parse:
    handler: src/handler.parse
    events:
      - http:
          method: get
          path: parse
